//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkflowConsoleApplication1.Mysec {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Mysec.IService")]
    public interface IService {
        SecretResponse SecretResponse
        {
            get;
            set;
        }
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/Secret", ReplyAction="http://tempuri.org/IService/SecretResponse")]
        WorkflowConsoleApplication1.Mysec.SecretResponse Secret(WorkflowConsoleApplication1.Mysec.SecretRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/Secret", ReplyAction="http://tempuri.org/IService/SecretResponse")]
        System.Threading.Tasks.Task<WorkflowConsoleApplication1.Mysec.SecretResponse> SecretAsync(WorkflowConsoleApplication1.Mysec.SecretRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Secret", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SecretRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int low;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int up;
        
        public SecretRequest() {
        }
        
        public SecretRequest(int low, int up) {
            this.low = low;
            this.up = up;
        }

        public IService IService
        {
            get
            {
                throw new System.NotImplementedException();
            }
            set
            {
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SecretResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SecretResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int sec;
        
        public SecretResponse() {
        }
        
        public SecretResponse(int sec) {
            this.sec = sec;
        }

        public WorkflowConsoleApplication1.Mycheck.checkNumberRequest checkNumberRequest
        {
            get
            {
                throw new System.NotImplementedException();
            }
            set
            {
            }
        }
    }
}
