<?xml version="1.0" encoding="utf-8"?><Database Name="CoursesDb" Class="CoursesClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=(LocalDB)\v11.0;AttachDbFilename=|DataDirectory|\CoursesDb.mdf;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="CoursesDbConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Instructors" Member="Instructors">
    <Type Name="Instructors">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="NChar(20)" CanBeNull="true" />
      <Column Name="LastName" Type="System.String" DbType="NChar(20)" CanBeNull="true" />
      <Column Name="OfficeNum" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="Courses" Type="System.String" DbType="NChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.myCourse" Member="myCourses">
    <Type Name="myCourse">
      <Column Name="CourseId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CourseCode" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="Title" Type="System.String" DbType="NChar(50)" CanBeNull="true" />
      <Column Name="Instructor" Type="System.String" DbType="NChar(20)" CanBeNull="true" />
      <Column Name="Cap" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
    </Type>
  </Table>
</Database>